version: "3.9"

services:
  # --- DATABASE ---
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - user_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  # --- INFRASTRUCTURE: RABBITMQ ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # --- BACKEND SERVICES ---
  user-service:
    build: ./services/user-service
    container_name: user-service
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/user_db?charset=utf8mb4
      - JWT_SECRET_KEY=AESP_Secret_Key_2026_Trong_Pro_AESP_2026_Upgrade
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/payment_db?charset=utf8mb4
      - USER_SERVICE_URL=http://user-service:5000/internal/upgrade-package
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  subscription-service:
    build: ./services/subscription-service
    container_name: subscription-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/subscription_db?charset=utf8mb4
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  ai-core-service:
    build: ./services/AI-core-service
    container_name: ai-core-service
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/xdpm?charset=utf8mb4
      - GROQ_API_KEY=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
      - JWT_SECRET_KEY=AESP_Secret_Key_2026_Trong_Pro_AESP_2026_Upgrade
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - app-network

  mentor-management-service:
    build: ./services/mentor-management-service
    container_name: mentor-management-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/user_db?charset=utf8mb4
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=AESP_Secret_Key_2026_Trong_Pro_AESP_2026_Upgrade
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  analytics-service:
    build: ./services/analytics-service
    container_name: analytics-service
    ports:
      - "5003:5003"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+pymysql://root:root@user-db:3306/analytics_db?charset=utf8mb4
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET_KEY=AESP_Secret_Key_2026_Trong_Pro_AESP_2026_Upgrade
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  # --- GATEWAY & FRONTEND ---
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend-react/dist:/usr/share/nginx/html/dist:ro
      - ./frontend/admin:/usr/share/nginx/html/admin:ro
      - ./frontend/mentor:/usr/share/nginx/html/mentor:ro
    depends_on:
      user-service:
        condition: service_started
      payment-service:
        condition: service_started
      subscription-service:
        condition: service_started
      mentor-management-service:
        condition: service_started
      ai-core-service:
        condition: service_started
      analytics-service:
        condition: service_started
    networks:
      - app-network

  # --- ADDITIONAL TOOLS ---
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=trong_password_123456
    volumes:
      - ./nifi-drivers:/opt/nifi/nifi-current/lib/drivers
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_flow:/opt/nifi/nifi-current/flowfile_repository
      - nifi_db_repo:/opt/nifi/nifi-current/database_repository
    networks:
      - app-network
  
  phpmyadmin:
     image: phpmyadmin:latest
     container_name: app-phpmyadmin
     environment:
       PMA_HOST: user-db
     ports:
       - "8080:80"
     depends_on:
       user-db:
         condition: service_healthy
     networks:
       - app-network
  #grafana     
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

volumes:
  user_db_data:
  nifi_conf:
  nifi_flow:
  nifi_db_repo:

networks:
  app-network:
    driver: bridge